### ISSUE TITLE
Fix SMS Carrier picker on Place Holds scene

### ISSUE THREAD

**Issue by kenstir** [kenstir/hemlock-ios#10]
Beta feedback:

> An SMS carrier is is pre-selected. Recommend that field be empty when customers go to the hold page. 

> The list for SMS carrier is all over the place alphabetically. Recommend the carriers be alphabetized.

**Comment by kenstir** [comment]
If the sms carrier is empty, and the SMS switch is on, then we need an alert when the Place Hold button is pressed.

**Comment by erikcx** [comment]
Fixed in erik_dev0729
