### ISSUE TITLE
Items due today are showing as overdue

### ISSUE THREAD

**Issue by wsmoak** [kenstir/hemlock-ios#32]
Items due on the current day are showing an (overdue) indicator, but this is not correct.

It shouldn't show overdue until the day _after_ the due date.

**Comment by wsmoak** [comment]
It appears to be happening here:
https://github.com/kenstir/hemlock-ios/blob/632047554510e3840f0cf64af7b9e5029734254a/Source/Scenes/Checkouts/CheckoutsViewController.swift#L209-L215

**Comment by kenstir** [comment]
Good catch and thanks!  The date is from the API and so should be parsed with the ISO date formatter.  It'll take a while before a new version is available through the app store.  If you'd like to become a Beta tester, sign up at https://testflight.apple.com/join/WGA6MuWl or send an email to kenstir.apps@gmail.com

**Comment by kenstir** [comment]
Actually fixed in 90eeb41
