### ISSUE TITLE
Library info - Library Location button partially cut off when Dynamic Type adjusted larger than default

### ISSUE THREAD

**Issue by mitchcohen** [kenstir/hemlock-ios#36]
On the Library screen, the Library Location button is partially cut off when Dynamic Type is adjusted larger than default.  See screenshots (including on of the setting used). 

![IMG_6229](https://user-images.githubusercontent.com/102565/103462621-7d215600-4cf4-11eb-97bb-70f9a7d02f16.PNG)
![IMG_6230](https://user-images.githubusercontent.com/102565/103462624-827ea080-4cf4-11eb-9043-06b948ae5d93.PNG)

**Comment by kenstir** [comment]
Fixed in 0a4500be85ee737b4899b72437ee67dadf3018ee
