### ISSUE TITLE
Main page - show card holder's name on main view

### ISSUE THREAD

**Issue by mitchcohen** [kenstir/hemlock-ios#38]
I manage the accounts for my family.  It would be very helpful to show the current card holder's name on the main page.

**Comment by kenstir-unity** [comment]
Hi Mitch,

the account name *is* displayed on the main page, between the app name and the button list.  It is formatted as a group header, in smallcaps, dark grey on light grey.

**Comment by kenstir** [comment]
Hi Mitch,

the account name is already displayed on the main page, between the app name and the button list. It is formatted as a group header, in smallcaps, dark grey on light grey.

**Comment by mitchcohen** [comment]
@kenstir. Thanks for the quick feedback!  I could have been more clear with my description.

I do see the string labeled as “Username” on the web site.  At least for my library, this defaults to the Active Barcode, a long numeric string.

I’m hoping to see the account holder’s name, shown as “Name” on the web site.  At least for my library, this is my first name followed by my last name.

If you think I should already be seeing the first/last name on the app, then something else is going on.

Thanks!

**Comment by kenstir** [comment]
@mitchcohen I think you are asking for the same thing here as in issue #39 -- using the account holder's first name *if* you logged in using the barcode.  I personally renamed all my family accounts that I login using the custom username.  My point here is that whatever you use to login, barcode or username, that string shows up on the main screen and also on the account switcher.  You can achieve what you want today by visiting /eg/opac/myopac/update_username on all your family accounts and customizing the username.

I'll leave this open in case we decide to default to displaying the full name in cases where the username is not customized.  Some consortiums (not CW MARS apparently) assign a custom username when setting up the initial account.  So I don't know yet widely applicable such a change would be.

**Comment by mitchcohen** [comment]
Yes, they are similar requests, to use the first/last name (here on the main page, #39 on the account switcher).  My experience is only with my family’s accounts, which all had the username set as the barcode number.  I did change my username, but I doubt many users do this.  It’s possible we’re in the minority, and CW MARS generally sets this to something else.  I can look into that if helpful.  Perhaps display both first/last name and username.

**Comment by kenstir** [comment]
Fixed in c35f5c70c12e245c436afa049acca28862bf818a
