### ISSUE TITLE
Account switcher - show card holders' names

### ISSUE THREAD

**Issue by mitchcohen** [kenstir/hemlock-ios#39]
I manage the accounts for my family.  It would be very helpful to show the card holders' names in that account switcher, instead of only the account numbers.  (I know account numbers can be changed on the web site, but I suspect that's not a widely-used feature.)

**Comment by kenstir** [comment]
Hi Mitch,

This is a reasonable idea, though there isn't a whole lot of horizontal space in that action sheet.  The names in the account switcher are the same as whatever you login with, so it would be reasonable to substitute the user's first name if you login via barcode.

You can't change your account number, but you can change your username and login with that.  The URL is HOSTNAME/eg/opac/myopac/update_username

**Comment by kenstir** [comment]
Fixed in 9706e05c8f89b1f91956f5ca20988a1193bd76a4
