### ISSUE TITLE
Implement Dynamic Type support on Search Results view

### ISSUE THREAD

**Issue by mitchcohen** [kenstir/hemlock-ios#40]
While working on #35 (Dynamic Type on Item Details) I looked into doing the same for Search Results.  The basics of this are very easy.  In XResultsTableNode.swift, replace the fixed sizes with the dynamic equivalent.  For example, replace the 16 in titleTextAttributes with UIFont.preferredFont(forTextStyle: .callout).pointSize).

It turns out, however, that the cell row height is fixed, resulting in the Format (Book, E-audio, etc) being vertically truncated on larger-than-default sizes.  So part of this issue is to adopt self-sizing cells, or whatever the equivalent is in Texture.

**Comment by kenstir** [comment]
Fixed initially in 2d92e10eaf44e8395032f260b7fce47184b0e1b0 and updated since then.
