### ISSUE TITLE
Item Description initially shows data from prior item

### ISSUE THREAD

**Issue by mitchcohen** [kenstir/hemlock-ios#44]
I see this a lot, but not sure how consistent this is.

Steps:

1. Search for something
2. Display first item found; no trouble
3. Go back to search results
4. Display second item found.  Details of first item are shown very briefly, then replaced by second item.
5. Repeat display of second item: Details of first item are shown again, and again replaced by second item.

In attached screen recording, I'd searched for Ron Galella.  Before recording I viewed the first item, _Smash His Camera_.  The recording shows me tapping the second item (_Jacqueline_) three times.  Each time, _Smash His Camera_ shows first, before being replaced by _Jacqueline_.

https://user-images.githubusercontent.com/102565/149805284-1effa66f-3ca2-4d48-9915-2025e620183a.mov

**Comment by kenstir** [comment]
This is 100% consistent.   The first item in the list always shows first, then in [viewDidAppear](https://github.com/kenstir/hemlock-ios/blob/8dc32bc920f79e2c11591d930ecc570ef04bc0e7/Source/Scenes/Details/XDetailsPagerViewController.swift#L64) we call scrollToPage.  Maybe one of the options described in https://github.com/TextureGroup/Texture/issues/133 would work?

As usual I'm open to PRs.

**Comment by kenstir** [comment]
This was fixed long back in version 2.6.1 by replacing AsyncDisplayKit with native UIPageControl.
