### ISSUE TITLE
Ability to remove accounts 

### ISSUE THREAD

**Issue by arifell** [kenstir/hemlock-ios#45]
Use case:
I use the app on my phone to manage the accounts of 6 members of my household.
We recently changed library card numbers.
I am able to add the new numbers but not remove the old ones…

**Comment by kenstir** [comment]
Yikes, what an oversight, thanks for the report!  In 3 years with this feature nobody has brought this to my attention.  I am looking into it.

**Comment by kenstir** [comment]
If you have a suggestion for an app that does it well, I am all ears.  If you say "Instagram", I will tell you they have 300+ engineers to my 1, so it may not be the easiest example to follow.  But that's the example I used when implementing it initially.

**Comment by arifell** [comment]
I don’t know if this is a great example…
The peloton app on their (android) based screen does have a fairly easy
method of adding/removing users from a particular device

I haven’t tried this functionality on an iOS device, though…

**Comment by kenstir** [comment]
Hi Ari, you filed this issue against the iOS app but you cite an Android app as an example.  Can you confirm you are reporting this issue on the iOS version of the CW MARS app?  The Android app uses the system Accounts system, and there you can remove accounts through the Settings app.

**Comment by arifell** [comment]
Yes, the issue is an IOS issue.
you asked about examples where this is done well, and in the same breath
said the "Instagram" is not a good example, because that have 300+
engineers.  so I did not suggest Instagram, Amazon, or Google, related
apps, since they too have a large workforce of developers.
the only other example I use with multiple user management is not an IOS
example.
since our conversation, though, I've been exposed to other IOS apps which
do this well - here are a few:
Mastodon for iPhone and iPad
<https://apps.apple.com/us/app/mastodon-for-iphone-and-ipad/id1571998974>
tooot - fediverse and Mastodon
<https://apps.apple.com/us/app/tooot-fediverse-and-mastodon/id1549772269>

**Comment by kenstir** [comment]
Thank you for confirming and I appreciate the references.  I will check them out for inspiration.

**Comment by kenstir** [comment]
In version 3.1.2, there is a new "Clear All Accounts" action.  It's not exactly what you asked for, but it's much less work, and you can add back the accounts you want.  Note that if you want to use usernames rather than barcodes to login, you can set that up [under My Account >> Preferences in the old catalog website](https://bark.cwmars.org/eg/opac/myopac/prefs).  When/if you get a new barcode, your username will not change.

It's not through App Review yet, but when it is you could test it by joining the beta test program.   Reply and I'll send you a link.  Sorry it took so long.

**Comment by arifell** [comment]
Thank you, I’m willing to be a beta user.

do you know when this feature will go live in the production version?

**Comment by kenstir** [comment]
I'm willing to put it into production as soon as I'm sure it works for someone other than me.  If that's you, I'd be grateful!  I'll update this issue when it gets through App Review; you can't join the Beta using a link when the build is waiting for review.

**Comment by arifell** [comment]
Excellent, looking forward to it, thank youOn Dec 29, 2024, at 20:39, kenstir ***@***.***> wrote:﻿
I'm willing to put it into production as soon as I'm sure it works for someone other than me.  If that's you, I'd be grateful!  I'll update this issue when it gets through App Review; you can't join the Beta using a link when the build is waiting for review.

**Comment by kenstir** [comment]
Well that took longer than usual, but hey it's the holidays.  Here's the link to sign up to test: https://testflight.apple.com/join/onTSXB0J

**Comment by arifell** [comment]
Thank you.
update works

**Comment by kenstir** [comment]
One minor tweak to the alert text colors and I'll release it.  Thanks for the quick review!
